#!/usr/bin/env python3
"""Build the installer with a Finder background bookmark generated by macOS."""
import pathlib
import os
import subprocess
import sys

import dmgbuild
from ds_store import DSStore, DSStoreEntry

ROOT = pathlib.Path(__file__).resolve().parent.parent


def main():
    mount = None

    def callback(event):
        nonlocal mount
        if event.get("command") == "hdiutil::attach" and event["type"] == "command::finished":
            for entity in event["output"].get("system-entities", []):
                if "mount-point" in entity:
                    mount = pathlib.Path(entity["mount-point"])
        if event.get("operation") == "dsstore::create" and event["type"] == "operation::finished":
            if mount is None:
                raise RuntimeError("Missing disk image mount point")
            # mac_alias's synthetic bookmark fails to resolve on current macOS.
            # Use Foundation's native bookmark and verify it before packaging.
            result = subprocess.run([
                "swift", str(ROOT / "scripts" / "dmg-bookmark.swift"),
                str(mount / ".background.tiff"),
            ], check=True, capture_output=True)
            with DSStore.open(str(mount / ".DS_Store"), "r+") as store:
                store.insert(DSStoreEntry(".", b"pBBk", b"blob", result.stdout))
            # Packaging must not alter the already signed application bundle.
            app = mount / pathlib.Path(os.environ["REVVY_APP"]).name
            subprocess.run(["codesign", "--verify", "--deep", "--strict", str(app)], check=True)

    dmgbuild.build_dmg(sys.argv[1], "Revvy", settings_file=str(ROOT / "scripts" / "dmg-settings.py"), callback=callback)


if __name__ == "__main__":
    main()
